### ISSUE TITLE
Use github.com/pkg/errors exclusively

### ISSUE THREAD

**Issue by sehqlr** [asteris-llc/converge#300]
We should use the errors package from pkg for all of our error reporting. Our components interact in many ways, across the stack and execution time, so we need really good error reporting. With the pkg/errors Wrap and Wrapf functions, we can make sure that our error messages contain enough context for core contributors and module writers alike.

**Comment by BrianHicks** [comment]
Where are we *not* using it?

**Comment by sehqlr** [comment]
There a lot of calls to `fmt.Errorf`, for example. The other thing is that all of the times we do
```
thing, err := functionCall(params)
if err != nil {
    return nil, err
}
```
it really should be
```
thing, err := functionCall(params)
if err != nil {
    return nil, errors.Wrap(err, "context for error message")
}
```
If we make sure that all of our errors are wrapped with helpful messages, that will be a much better UX. In the cases where we are checking the contents of an error message, and we don't need the context, we can call `errors.Cause` to get the underlying message.

**Comment by BrianHicks** [comment]
fmt.Errorf is actually completely fine where we're constructing a new error message out of nothing. It doesn't have a stack trace attached but that's just fine in most cases. The last I looked, that was the only case in which we were using Errorf.

As for *always* wrapping: that's one thing that seems good but as you get into the weeds on it you realize it's not the case. Some error values we need exactly (like the error raised from renderer.Render if it needs to be turned into a ThunkTask.) Other times we're actually wrapping *too* much. For example, if a file fails to load, the filename is in there several times because we're wrapping at each level. Judicious use of wrapping is super helpful, but it can easily be too much.

That said, if you have any ideas about *specific cases* where we either should or should not use wrapping, go ahead and attach them to this issue so we can discuss and fix them individually.

**Comment by BrianHicks** [comment]
@sehqlr any update? I'm going to close this issue if we don't get a specific list of cases we can discuss.

**Comment by sehqlr** [comment]
I don't have a specific list, no. Closing.
