### ISSUE TITLE
Mutable TaskStatus results in apply losing differences

### ISSUE THREAD

**Issue by rebeccaskinner** [asteris-llc/converge#374]
During apply we lose status information that results in no differences being show during output.  The root cause is that because the `TaskStatus` being returned by modules is the `Task` with an embedded `resource.Status`, so when we call `Check` with `plan.Result.Task` it mutates the `apply.Result.Status` that we have stored.

The fix is to separate out tasks from status, have each module return an actual status.  Reflection should automatically populate a `map[string]interface{}` inside of the status to handle lookups, and then both the task and the status should be made immutable.

**Comment by BrianHicks** [comment]
Proposal, from the module author's perspective: separate Task and Status.

Lookups will be handled with struct tags on the task.

```go
type Directory struct {
  Destination string `export:"destination"`
}
```

The above configuration would cause a field `destination` to be available on lookup. If the `lookup` struct tag is not present, the field would not be exported.

Generated fields (like a full image tag from `docker.image`) could also be represented:

```go
type Image struct {
  // existing fields
  FullTag string `export:"full-tag"`
}
```

In this case, `FullTag` would be set by `Image.Apply` rather than from the preparer.

The implementation of Plan and Apply would construct new Statuses instead of embedding them, and the fields would be added by the runtime. Existing semantics (other than embedding) should not change.

We should also be able to generate documentation from these lookup tags.

---

From an implementation perspective:

1. Add a `fields` map to Status
2. Add code to all places statuses are created to introspect tags from the task and export to the fields struct. This may work better as a wrapper, á la `resource.Preparer`. The code to do this could probably live in a method on the status.
3. Change lookup code to use the `fields` map instead.
4. Remove embeds from existing modules and test that wrapping works correctly with their exports
5. Modify documentation generation code to automatically generate docs for the new exports.
